# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: policy.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'policy.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0cpolicy.proto\x12\x06policy\".\n\x17InitializeOrStopRequest\x12\x13\n\x0bpolicy_name\x18\x01 \x01(\t\"<\n\x18InitializeOrStopResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\"o\n\rDecideRequest\x12\x11\n\troleNames\x18\x01 \x03(\t\x12&\n\x06levels\x18\x02 \x03(\x0b\x32\x16.policy.IndicatorLevel\x12#\n\tresources\x18\x03 \x03(\x0b\x32\x10.policy.Resource\"|\n\x0e\x44\x65\x63ideResponse\x12\x38\n\tdecisions\x18\x01 \x03(\x0b\x32%.policy.DecideResponse.DecisionsEntry\x1a\x30\n\x0e\x44\x65\x63isionsEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\x08:\x02\x38\x01\"g\n\x0eIndicatorLevel\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\x02\x12\r\n\x05isMet\x18\x03 \x01(\x08\x12\x11\n\tthreshold\x18\x04 \x01(\x02\x12\x16\n\x0e\x61ssociatedRole\x18\x05 \x01(\t\"\'\n\x08Resource\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\x02\x32\xe4\x01\n\rPolicyService\x12O\n\nInitialize\x12\x1f.policy.InitializeOrStopRequest\x1a .policy.InitializeOrStopResponse\x12\x37\n\x06\x44\x65\x63ide\x12\x15.policy.DecideRequest\x1a\x16.policy.DecideResponse\x12I\n\x04Stop\x12\x1f.policy.InitializeOrStopRequest\x1a .policy.InitializeOrStopResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'policy_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_DECIDERESPONSE_DECISIONSENTRY']._loaded_options = None
  _globals['_DECIDERESPONSE_DECISIONSENTRY']._serialized_options = b'8\001'
  _globals['_INITIALIZEORSTOPREQUEST']._serialized_start=24
  _globals['_INITIALIZEORSTOPREQUEST']._serialized_end=70
  _globals['_INITIALIZEORSTOPRESPONSE']._serialized_start=72
  _globals['_INITIALIZEORSTOPRESPONSE']._serialized_end=132
  _globals['_DECIDEREQUEST']._serialized_start=134
  _globals['_DECIDEREQUEST']._serialized_end=245
  _globals['_DECIDERESPONSE']._serialized_start=247
  _globals['_DECIDERESPONSE']._serialized_end=371
  _globals['_DECIDERESPONSE_DECISIONSENTRY']._serialized_start=323
  _globals['_DECIDERESPONSE_DECISIONSENTRY']._serialized_end=371
  _globals['_INDICATORLEVEL']._serialized_start=373
  _globals['_INDICATORLEVEL']._serialized_end=476
  _globals['_RESOURCE']._serialized_start=478
  _globals['_RESOURCE']._serialized_end=517
  _globals['_POLICYSERVICE']._serialized_start=520
  _globals['_POLICYSERVICE']._serialized_end=748
# @@protoc_insertion_point(module_scope)
